### ISSUE TITLE
GTA V process not being detected as case-sensitive process names are used.

### ISSUE THREAD

**Issue by leHeix** [Hyaxe/discord-rich-presence#1]
When playing GTA V, Rich Presence will not detect it as it's assigned as "gta5.exe" while process name is actually "GTA5.exe"

This could be fixed by modifying [line 125 in main.py](https://github.com/Hyaxe/discord-rich-presence/blob/master/main.py#L125) 

Correct code:
```python
if utils.checkIfProcessRunning('GTA5.exe'):
```

**Comment by RealAtom** [comment]
fixed
